# Generated by Django 2.0.7 on 2018-07-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='xxxxx', max_length=200),
        ),
    ]
